 version: "3"
 services:
   hub:
      image: selenium/hub:3.14
      ports:
         - "4444:4444"
   chrome:
      image: selenium/node-chrome:3.14
      depends_on:
         - hub
      environment:
         - HUB_HOST=hub
   firefox:
      image: selenium/node-firefox:3.14
      depends_on:
         - hub
      environment:
         - HUB_HOST=hub
   search-module:
      image: selenium-docker
      shm_size: '1gb'
      depends_on:
         - chrome
         - firefox
      environment:
         - BROWSER=firefox
         - HUB_HOST=hub
         - MODULE=search-module.xml
      volumes:
         - ./search-result:/usr/share/umesh/test-output   
   search-module2:
      image: selenium-docker
      shm_size: '1gb'
      depends_on:
         - chrome
         - firefox
      environment:
         - BROWSER=chrome
         - HUB_HOST=hub
         - MODULE=search-module.xml
      volumes:
         - ./search-result2:/usr/share/umesh/test-output
   
         